# Generated by Django 4.0.6 on 2022-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersdirectory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstable',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
