# Generated by Django 4.0.6 on 2022-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersdirectory_app', '0002_alter_teacherstable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstable',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
