# Generated by Django 4.0.6 on 2022-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersdirectory_app', '0003_alter_teacherstable_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstable',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profilepic/default.JPG', null=True, upload_to='profilepic/'),
        ),
    ]
